[package]
name = "moldyn_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "0.8"
serde = {version="1.0.164", features = ["derive"]}
nalgebra = {version="0.32.2", features = ["serde-serialize"]}
lazy_static = "1.4.0"
rayon = "1.7.0"

[dev-dependencies]
tempdir = "0.3.7"
rand = "0.8.5"