[package]
name = "moldyn_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
moldyn_core = { path = "../core" }
nalgebra = "0.32.2"
rayon = "1.7.0"
lazy_static = "1.4.0"
ron = "0.8"
serde = {version="1.0.164", features = ["derive"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }